blog/blog/urls.py
#coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
admin.autodiscover()
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),    
    url(r'^comments/', include('django.contrib.comments.urls')),
)
urlpatterns += patterns((''),
    (r'^sblog/', include('sblog.urls')),
)

blog/sblog/urls.py
#coding=utf-8
from django.conf.urls import *


urlpatterns = patterns(('sblog.views'),
    url(r'^bloglist/$', 'blog_list', name='bloglist'),
    url(r'^blog/(?P<id>\d+)/$', 'blog_show', name='detailblog'),
    url(r'^blog/tag/(?P<id>\d+)/$', 'blog_filter', name='filtrblog'),
    url(r'^blog/add/$', 'blog_add', name='addblog'),
    url(r'^blog/(?P<id>\w+)/update/$', 'blog_update', name='updateblog'),
    url(r'^blog/(?P<id>\w+)/del/$', 'blog_del', name='delblog'),
)

blog/sblog/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    """docstring for Tags"""
    tag_name = models.CharField(max_length=20, blank=True)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.tag_name


class Author(models.Model):
    """docstring for Author"""
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    def __unicode__(self):
        return u'%s' % (self.name)


class Blog(models.Model):
    """docstring for Blogs"""
    caption = models.CharField(max_length=50)
    author = models.ForeignKey(Author)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u'%s %s %s' % (self.caption, self.author, self.publish_time)

    class Meta:
        ordering = ['-publish_time']

blog/sblog/forms.py
from django import forms

class BlogForm(forms.Form):
    caption = forms.CharField(label='title', max_length=100)
    content = forms.CharField(widget=forms.Textarea)
class TagForm(forms.Form):
    tag_name = forms.CharField()

blog/sblog/views.py
# Create your views here.
#coding=utf-8
from django.shortcuts import render_to_response
from sblog.models import Blog
from django.http import Http404
from sblog.models import Tag
from django.http import HttpResponseRedirect
from django.template import RequestContext
from sblog.models import Author
from sblog.forms import BlogForm
from sblog.forms import TagForm


def blog_list(request):
    blogs = Blog.objects.all()
    return render_to_response("blog_list.html", {"blog": blogs})
def blog_show(request, id=''):
    try:
        blog = Blog.objects.get(id=id)
    except Blog.DoesNotExist:
        raise Http404
    return render_to_response("blog_show.html", {"blog": blog})
def blog_filter(request, id=''):
    tags = Tag.objects.all()
    tag = Tag.objects.get(id=id)
    blogs = tag.blog_set.all()
    return render_to_response("blog_filter.html",
        {"blogs": blogs, "tag": tag, "tags": tags})
def blog_add(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        tag = TagForm(request.POST)
        if form.is_valid() and tag.is_valid():
            cd = form.cleaned_data
            cdtag = tag.cleaned_data
            tagname = cdtag['tag_name']
            for taglist in tagname.split():
                Tag.objects.get_or_create(tag_name=taglist.strip())
            title = cd['caption']
            author = Author.objects.get(id=1)
            content = cd['content']
            blog = Blog(caption=title, author=author, content=content)
            blog.save()
            for taglist in tagname.split():
                blog.tags.add(Tag.objects.get(tag_name=taglist.strip()))
                blog.save()
            id = Blog.objects.order_by('-publish_time')[0].id
            return HttpResponseRedirect('/sblog/blog/%s' % id)
    else:
        form = BlogForm()
        tag = TagForm(initial={'tag_name': 'notags'})
    return render_to_response('blog_add.html',
        {'form': form, 'tag': tag}, context_instance=RequestContext(request))
def blog_update(request, id=""):
    id = id
    if request.method == 'POST':
        form = BlogForm(request.POST)
        tag = TagForm(request.POST)
        if form.is_valid() and tag.is_valid():
            cd = form.cleaned_data
            cdtag = tag.cleaned_data
            tagname = cdtag['tag_name']
            tagnamelist = tagname.split()
            for taglist in tagnamelist:
                Tag.objects.get_or_create(tag_name=taglist.strip())
            title = cd['caption']
            content = cd['content']
            blog = Blog.objects.get(id=id)
            if blog:
                blog.caption = title
                blog.content = content
                blog.save()
                for taglist in tagnamelist:
                    blog.tags.add(Tag.objects.get(tag_name=taglist.strip()))
                    blog.save()
                tags = blog.tags.all()
                for tagname in tags:
                    tagname = unicode(str(tagname), "utf-8")
                    if tagname not in tagnamelist:
                        notag = blog.tags.get(tag_name=tagname)
                        blog.tags.remove(notag)
            else:
                blog = Blog(caption=blog.caption, content=blog.content)
                blog.save()
            return HttpResponseRedirect('/sblog/blog/%s' % id)
    else:
        try:
            blog = Blog.objects.get(id=id)
        except Exception:
            raise Http404
        form = BlogForm(initial={'caption': blog.caption, 'content': blog.content}, auto_id=False)
        tags = blog.tags.all()
        if tags:
            taginit = ''
            for x in tags:
                taginit += str(x) + ' '
            tag = TagForm(initial={'tag_name': taginit})
        else:
            tag = TagForm()
    return render_to_response('blog_add.html',
        {'blog': blog, 'form': form, 'id': id, 'tag': tag},
        context_instance=RequestContext(request))
def blog_del(request, id=""):
    try:
        blog = Blog.objects.get(id=id)
    except Exception:
        raise Http404
    if blog:
        blog.delete()
        return HttpResponseRedirect("/sblog/bloglist/")
    blogs = Blog.objects.all()
    return render_to_response("blog_list.html", {"blogs": blogs})

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}{% endblock %}              
    </title>
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    {% block extra_head %}
    {% endblock %}
</head>

<body>
    {% block body %}
        {% block header %}
            {# 任何每个页面都可能修改的文本区域的页面 #}
            {% block menu %}
            {# 你的菜单 (导航栏) 应该包含在这个区块中. 它是针对站点级的导航, 不是 每个页面专属的导航菜单. #}
            {% endblock %}
        {% endblock %}
        <div class="container">
        {% block content %}
            {# 这个区块用来放置页面正文内容. 任何页面正文内容都可能不一样. 它不 包含任何站点导航, 信息头, 页脚, 或其它任何属于 base 模板的东东. #}

            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="span9">                            
                        {% block article %}
                            {% block article_title %}
                                {% comment %}
                                用来指定 content 区块的 "title". 比如 blog 的标题. 
                                也可以用来 包含 content 内的导航 (译注: 比如提纲), 或其它类似的东东. 
                                大致都是些 页面中并非主要内容的东东. 
                                我不知道这个区块是否应该放到 content tag 内, 并且对应于前面建议的 content tag, 
                                是不是还需要一个 main_content 区块.
                                {% block [section]_menu %} {% block page_menu %}
                                这是对应于之前建议的 menu 区块. 用来导航一个章节或页面.
                                {% endcomment %}
                            {% endblock %}
                            {% block article_content %}{% endblock %}
                        {% endblock %}
                        
                        {% block article_menu %} {% endblock %}
                        {% block comments %} {% endblock %}
                        </div>
                        <div class="span3">
                            {% block aside %}
                                {% block tags %}{% endblock %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            {% endblock %}
            {% block footer %}
                {# 任何每个页面都可能修改的文本区域的页脚 #}
                <p>Thanks for visiting my site! </p>
            {% endblock %}
        {% endblock %}
    </div>
    <script src="../static/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/blog_base.html
{% extends "base.html" %}

{% block extra_head %}
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style> 
{% endblock %}   

{% block header %}
    {% block menu %}
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">  
                <a class="brand" href="#">BLOG</a>
                <ul class="nav">
                    <li class="active divider-vertical">
                        <a href="{% url 'bloglist' %}">home</a>
                    </li>
                    <li>
                        <a href="#">about</a>
                    </li>
                    <li>
                        <a href="#">contact</a>
                    </li>
                </ul>                     
            </div>                
        </div>
    </div>    
    {% endblock %}
{% endblock %}

blog/templates/sblog/blog_add.html
{% extends "blog_base.html" %}
 
 {% block title %} 发布文字 {% endblock %}   
 
 
 {% block article %} 
 
 <form action="" method="post">
     {% csrf_token %} 
     <div class="field">
         <label for="id_caption">Title: </label>
         {% if form.caption.errors %}
         <div class="alert alert-error">
             {{ form.caption.errors }}          
         </div>
         {% endif %}
         {{ form.caption }}
     </div>
     <div class="field">        
         <label for="id_content">Content: </label>
         {% if form.content.errors %}
         <div class="alert alert-error">
             {{ form.content.errors }}
         </div>
         {% endif %}
         {{ form.content }}
     </div>
      <div class="field">
        <label for="id_tag">tags</label>
        {% if tag.tag_name.errors %}
        <div class="alert alert-error">
            {{ tag.tag_name.errors }}
        </div>
        {% endif %}
        {{ tag.tag_name }}
 </div>
     <div class="form-actions">
         <input class="btn btn-primary" type="submit" value="save and add">
     </div>
 </form>

 {% endblock %}

blog/templates/sblog/blog_list.html
{% extends "blog_base.html" %}

{% block title %} {{ blog.caption }} {% endblock %}


{% block article %} 

<div class="content">
    <article class="content-main">
    {% block article_title %}
        <h2>{{ blog.caption }}</h2>
    {% endblock %}
    <p class="muted">
        <i class="icon-user"></i><small> {{ blog.author }}</small>  
        <i class="icon-time"></i><small> {{ blog.publish_time }}</small>
    </p>
        <section>
        <div class="blog-content">
            {% block article_content %}
                {{ blog.content }}
            {% endblock %} 
        </div>
    </section>
    <section>
        <div class="row-fluid post-info">
            <div class="span3">
                <p>  
                    <i class="icon-tag"></i>
                    {% for tag in blog.tags.all %}
                         <small class="muted"> {{ tag }} </small>
                    {% endfor %}
                </p>  
            </div>
            {% comment %}
            <div class="span2 offset7">
                <a href="{% url delblog blog.id %}" title="delete"><i class="icon-trash"></i></a>
                <a href="{% url updateblog blog.id %}" title="edit"><i class="icon-edit"></i></a>
                <a href="#cmt" title="comment"><i class=" icon-comment"></i></a>
            </div>
            {% endcomment %}
        </div>
    </section>    
    </article>
    <hr>
</div>    
{% endblock %}

blog/templates/sblog/blog_show.html
{% extends "blog_base.html" %}

{% block title %} {{ blog.caption }} {% endblock %}


{% block article %} 

<div class="content">
    <article class="content-main">
    {% block article_title %}
        <h2>{{ blog.caption }}</h2>
    {% endblock %}
    <p class="muted">
        <i class="icon-user"></i><small> {{ blog.author }}</small>  
        <i class="icon-time"></i><small> {{ blog.publish_time }}</small>
    </p>
        <section>
        <div class="blog-content">
            {% block article_content %}
                {{ blog.content }}
            {% endblock %} 
        </div>
    </section>
    <section>
        <div class="row-fluid post-info">
            <div class="span3">
                <p>  
                    <i class="icon-tag"></i>
                    {% for tag in blog.tags.all %}
                         <small class="muted"> {{ tag }} </small>
                    {% endfor %}
                </p>  
            </div>
            <div class="span2 offset7">
                <a href="{% url 'delblog' blog.id %}" title="delete"><i class="icon-trash"></i></a>
                <a href="{% url 'updateblog' blog.id %}" title="edit"><i class="icon-edit"></i></a>
                <a href="#cmt" title="comment"><i class=" icon-comment"></i></a>
            </div>
        </div>
    <hr>
    </section>    
    </article>
    <hr>
</div>    
{% endblock %}